# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cairn < Formula
  desc "One orchestrator for quality, versioning, changelog, and commit hygiene across every language"
  homepage "https://github.com/IVIR3zaM/Cairn"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/IVIR3zaM/Cairn/releases/download/v0.2.2/cairn_darwin_amd64.tar.gz"
      sha256 "1625386c4496611e1c34ac58e57868d3e05137e35e3db81562a83b15e5e5cc24"

      define_method(:install) do
        bin.install "cairn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/IVIR3zaM/Cairn/releases/download/v0.2.2/cairn_darwin_arm64.tar.gz"
      sha256 "e25522fef9a026adc6d4df288e8f6ac0f75e36a06544f040c469a26b107ff106"

      define_method(:install) do
        bin.install "cairn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/IVIR3zaM/Cairn/releases/download/v0.2.2/cairn_linux_amd64.tar.gz"
      sha256 "e29f3d8391e74fd8557f03a5b0b9db94414ef5db4a018f6494a76e7b41a142d8"
      define_method(:install) do
        bin.install "cairn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/IVIR3zaM/Cairn/releases/download/v0.2.2/cairn_linux_arm64.tar.gz"
      sha256 "415fbf031f743b46f1719ed9e6f0404b322d94a1b0f6c21285fa5094e9f406bb"
      define_method(:install) do
        bin.install "cairn"
      end
    end
  end

  test do
    system "#{bin}/cairn", "--version"
  end
end
