# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cairn < Formula
  desc "One orchestrator for quality, versioning, changelog, and commit hygiene across every language"
  homepage "https://github.com/IVIR3zaM/Cairn"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/IVIR3zaM/Cairn/releases/download/v0.1.0/cairn_darwin_amd64.tar.gz"
      sha256 "42be8e14a781071d69eedc7ba8be185f02d10ac966acfa7ade35d9165e95387a"

      define_method(:install) do
        bin.install "cairn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/IVIR3zaM/Cairn/releases/download/v0.1.0/cairn_darwin_arm64.tar.gz"
      sha256 "8f2d2311a625b85502c793a7eff21d8c7bcfb75dc65e4b45dd86676cfe0f847d"

      define_method(:install) do
        bin.install "cairn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/IVIR3zaM/Cairn/releases/download/v0.1.0/cairn_linux_amd64.tar.gz"
      sha256 "c74c23308c8f8dba29c0df8023501640809b6416af4a5c066128cf7baaeecebd"
      define_method(:install) do
        bin.install "cairn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/IVIR3zaM/Cairn/releases/download/v0.1.0/cairn_linux_arm64.tar.gz"
      sha256 "ed411de6ac2db903fb658d4d77e45aea19f7e001ee790f8de4334d0232835c18"
      define_method(:install) do
        bin.install "cairn"
      end
    end
  end

  test do
    system "#{bin}/cairn", "--version"
  end
end
